[features]
seeds = false
[programs.localnet]
mysolanaapp = "9uAaUCm71RDneCtCHHE7AfVYEL15p93YisrqHcfRDfZK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/chanchoi829/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
