[features]
seeds = false
[programs.localnet]
mysolanaapp = "6XM13ZB4vsCCnUU2WrHsoBtrY8zGPwbHGBzVU8AsG2Dp"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/chanchoi829/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
